### ISSUE TITLE
start server failed

### ISSUE THREAD

**Issue by dierbei** [second-state/microservice-rust-mysql#14]
![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/26c059a8-a640-4553-b111-648933cd2cb7)

I tried to use `wasmedge --env "DATABASE_URL=mysql://user:passwd@127.0.0.1:3306/mysql" order_demo_service.wasm
` to run the program, but the above error occurred, how can I solve it ?

**Comment by juntao** [comment]
You already have another server listening at that port.

**Comment by dierbei** [comment]
Thanks, successfully solved the problem.
