### ISSUE TITLE
Dockerfile build: unknown flag: link

### ISSUE THREAD

**Issue by dierbei** [second-state/microservice-rust-mysql#15]
![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/1cf11da6-dfb0-4e5d-85d0-9aa9a8e788c9)

I tried to build a image using Dockerfile and got this error.

**Comment by dierbei** [comment]
I think adding a .dockerignore file might build better.

**Comment by hydai** [comment]
Please use `buildx` to build the docker image:

```bash
docker buildx build -t wasm:1636 .
```

**Comment by dierbei** [comment]
> Please use `buildx` to build the docker image:
> 
> ```shell
> docker buildx build -t wasm:1636 .
> ```
Thanks, I solved the problem of building

**Comment by dierbei** [comment]
Another problem：
![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/f00f2f6d-ddff-48a8-a430-e8897b3f3a0b)

**Comment by hydai** [comment]
According to the docker-compose file, you will need to specify the platform to run it. 
Ref:
https://github.com/second-state/microservice-rust-mysql/blob/main/docker-compose.yml#L10

**Comment by dierbei** [comment]
> According to the docker-compose file, you will need to specify the platform to run it. Ref: https://github.com/second-state/microservice-rust-mysql/blob/main/docker-compose.yml#L10

You are right, but I have a problem when running.

![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/8d7c7514-bca8-4cb7-9819-dcdbd569c5cb)

I try to specify the architecture when building.

![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/a69b2502-8723-4a35-bf85-e8484fd694ff)

**Comment by dierbei** [comment]
My operating system is Ubuntu.

**Comment by hydai** [comment]
Have you installed the wasm-enabled runtime bundled docker, such as docker-desktop?

Also, you have to add an extra flag: `export BUILDX_NO_DEFAULT_ATTESTATIONS=1`
Ref: https://github.com/second-state/microservice-rust-mysql/commit/ac7bbed4db49ebdd18c044e4d3bdf6c51eebefa4

**Comment by dierbei** [comment]
> Have you installed the wasm-enabled runtime bundled docker, such as docker-desktop?
> 
> Also, you have to add an extra flag: `export BUILDX_NO_DEFAULT_ATTESTATIONS=1` Ref: [ac7bbed](https://github.com/second-state/microservice-rust-mysql/commit/ac7bbed4db49ebdd18c044e4d3bdf6c51eebefa4)

Am I supposed to do this right?

![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/eff6e349-3b80-468a-8b98-3fd9c8cd0207)

**Comment by hydai** [comment]
What's your docker version?

This is mine:
![CleanShot 2023-06-19 at 16 43 32](https://github.com/second-state/microservice-rust-mysql/assets/2776756/f502f18c-202a-4241-aa2c-53f75945e02d)

![CleanShot 2023-06-19 at 16 55 27](https://github.com/second-state/microservice-rust-mysql/assets/2776756/70ba7af1-f2a3-4ba3-aa9c-3deca32ae261)

**Comment by dierbei** [comment]
This is mine: 
![image](https://github.com/second-state/microservice-rust-mysql/assets/52097565/822d0d0e-a4d1-4121-86fb-18734f3e4c8b)

**Comment by dierbei** [comment]
> docker-desktop

I don't have docker-desktop installed, I only have terminal.

**Comment by juntao** [comment]
You will need Docker Desktop. 

Or 

Use the 24.0.0-beta-1 or above of dockerd. You do have to activate the containerd feature, put { "features": [ "containerd-snapshotter": true ] } in /etc/docker/daemon.json). 

You can download the build from http://download.docker.com (for debian for example it’s here: https://download.docker.com/linux/debian/dists/bullseye/pool/test/amd64/docker-ce_24.0.0~beta.1-1~debian.11~bullseye_amd64.deb).

**Comment by dierbei** [comment]
> You will need Docker Desktop.
> 
> Or
> 
> Use the 24.0.0-beta-1 or above of dockerd. You do have to activate the containerd feature, put { "features": [ "containerd-snapshotter": true ] } in /etc/docker/daemon.json).
> 
> You can download the build from http://download.docker.com (for debian for example it’s here: https://download.docker.com/linux/debian/dists/bullseye/pool/test/amd64/docker-ce_24.0.0~beta.1-1~debian.11~bullseye_amd64.deb).

Thanks, I'll try it later.

**Comment by dierbei** [comment]
I built successfully with Docker Desktop on MAXOS, thanks for your help.

**Comment by dierbei** [comment]
I have another question, is there a web framework that supports wasm better?
